### PR TITLE
Post ban appeals publicly on the site

### PR DESCRIPTION
**Pull request by gene-auber1**
These changes are to publicly post ban appeals that Bronystate has received (at least, the ones I'm aware of).  This brings Bronystate into compliance with its rule "Appeals will be posted publicly on the site".

Other than the introductory text and headings, the text is taken directly from ban appeals.

### CODE REVIEW

**Comment by CriticKitten** [comment]
The line that states that ban appeals will be posted publicly is an outdated rule that was missed in previous passes as part of the process to update the rules.  We have discussed it as a staff and determined that this rule is no longer necessary nor desirable.  We thank you for bringing it to our attention.

Furthermore, as to the specific appeal in question, you have already evaded your Discord ban on at least two occasions that I have records of, which (in accordance with the rules you are quoting) makes you ineligible for further appeals.

**Comment by CriticKitten** [comment]
Just wanted to add that you are welcome to discuss this with me on Discord if you would like a more thorough explanation of anything I've said here.

**Comment by gene-auber1** [comment]
CriticKitten is somehow still failing to understand.  There can be no productive discussion with him because he does not see me as a person with valid mental faculties, feelings, and intentions.  He has maintained for over two years that I am an "unbelievably dense child" and "ignorant dickweasel" who "think[s] everything is hate speech."  He cannot have that mentality and perceive me as capable of having a discussion with him.

**Comment by CriticKitten** [comment]
Alright, since you clearly will not let this drop, I am going to give you a very thorough and detailed evaluation of your second ban appeal, dated .  Specifically, I'm going to explain exactly why it's being rejected, and I'm going to explain a few other details as well because I think you have a very mistaken interpretation of things.

When we moved over to Discord, all of our former bans were lifted, including yours.  We did this because we wanted to give every user, even those who were serial violators of the rules, a chance to try again and rejoin the community.  Several members who used to be problems back in the day have done just that, reintegrated just fine and are still around now.  So, to that end, we as a staff made every effort to give you that second chance.  Yet, on your very first day back (mid-2019), you mistakenly accused us of upholding your ban on Discord when this was not true, and never apologized to any staff member for the mixup.  And the problems didn't end there.

Over the course of the next two months, instead of setting aside old grudges, you continued to attack and harass no less than **four** members of the community over things they had said weeks ago, months ago, and in some cases, even years ago.  As a result, you were demoted from regular status, and when you continued that behavior in our stream chat (which is also against the chat rules), you were banned from the Discord for good.  Not content with this, you evaded no less than two times before we finally had to disable our Titan embed (effectively closing the doors to our community) just to keep you from evading further.  And I'm told from multiple sources that you've also continued this behavior in other related communities, with similar results.

From any objective standpoint as an administrator, that's more than enough cause to keep you from returning all on its own.  But then you took it the extra step by harassing us via email, by posting attacks about us on other sites, and now, by coming to our Github and posting a pull request demanding a ban appeal.  And, having read the appeal itself, all I see is a post that suggests that *we* are the true problem, and that we should simply allow you back because of the "chan" origins of the community.  Suffice it to say, we don't feel that's a good justification at all.  You are not sorry for anything you've done, or anyone you've hurt along the way.  An appeal to "the freedom of the chans" is not an apology, it's actually the exact opposite.  It's demanding we apologize to you for perceived slights that, so far as I can tell, nobody in the community (regular or mod) agrees with.

Finally, I want to address this consistent attack on me and my character, because it really shows that you don't know much about the last two months.  I probably shouldn't say this, but I'm going to, because I'm tired of both myself and my team being maligned and slighted across every site that we have anything to do with.  So here goes: the only reason you were permitted to remain in the community as long as you were is because I was regularly telling our staff not to ban you.  I don't expect you to believe me, nor do I ultimately care if you do or not, but that's the reality of the situation here.  I admit that I felt somewhat bad for you and the way that things had been left off, and I wanted to give you an honest chance to reintegrate with this community, same as everyone else.

And instead of doing so, you made every conceivable effort to pursue those old grudges, each time making it harder and harder for me to explain to the rest of the staff why I disagreed with just banning you on the spot.  So for all of your personal attacks on me over the years and your consistent aggression, I want you to know that I was pretty much the only person involved in the process that was legitimately pulling for you.  That's why I kept saying, over and over, that I was open to you discussing things with me in Discord, because I wanted to give you a chance to hash things out.  Because I hoped, in vain, that you'd stop attacking my co-workers and friends if you were just able to vent your frustrations solely at me.  But you've closed that door yourself, and there is no reopening it now.

If there is anything left for me to say, it's this: I hope that you will take recent events and what I've said here as a sign that perhaps it's not everybody else that's the problem.  And maybe it will be the spark you need to make an earnest effort to better yourself.  However, even if you do, I want to be clear in saying that there will be no more appeals for you.  There is not a single member of our moderator team that is willing to hear your appeal, and you've burned out the last of any goodwill that I was willing to offer with your antics here, as well.  Our Github repository is not your personal Discord ban appeal site, and to use it as such is abuse.  To that end, since I unfortunately cannot trust you to stop posting here or let this go, I will be banning you from this repository for good in the near future, starting this Friday night.  That should give you a few days to read this and hopefully mull it over.

I hope that you treat the next community you elect to join with more respect than you've shown ours.  Goodbye.

**Pull request closed without merging**
